### ISSUE TITLE
Python3 not supported

### ISSUE THREAD

**Issue by vinyll** [jazzdd86/alpine-flask#1]
Alpine seems not to have a compatible version of _uwsgi_ plugin for Python3.

I had based [my project](https://github.com/vinyll/everywhere-api) on your image but I had to rewrite [a part of it](https://github.com/vinyll/everywhere-api/blob/master/Dockerfile) and base on some Debian.

**Comment by jazzdd86** [comment]
yeah, I know, that's why I am still on python 2.7 with this docker image.
UWSGI does not support musl right now, which is used in alpine instead of glibc. that's why there has to be an extra modification for uwsgi - therefore it cannot be compiled using pip.
I am using the alpine uwsgi package and that's only available for python2 right now.

**Comment by vinyll** [comment]
Have you done any test with Gunicorn instead of uwsgi or is it still a path to try out?

**Comment by jazzdd86** [comment]
never tried it. So I don't know if its running.

**Comment by jazzdd86** [comment]
done :-) uwsgi is now available for python3 in alpine. see branch or docker tag python3.
