### ISSUE TITLE
Installing flask-ask throws error code 1

### ISSUE THREAD

**Issue by IDmedia** [jazzdd86/alpine-flask#4]
Tried to use this image with a flask-ask app, but it throws the following error when it tries to install "cffi-1.11.2" (dependency):
`Command "python setup.py egg_info failed with error code 1 in /tmp/pip-build-_CC3oO/cffi`
Image: https://i.imgur.com/fWeYkb8.png

**Edit:** Installing these packages solves the issue. Possible to include them? :)
`apk add --no-cache openssl-dev libffi-dev gcc python-dev musl-dev`

**Comment by jazzdd86** [comment]
Hi, this is because the image has no way to build packages, just install prebuild or small packages with few dependencies. I am working on extending this image to be capable of building packages and its dependecies. But this will still take some time as I have very little freetime at the moment. But I think I will upload a new image after Christmas

**Comment by IDmedia** [comment]
Awesome thanks! Would it not be enough to add the libs I've mentioned to the Dockerfile? Looking forward to the next build. Enjoy Christmas and a happy new year to you and your family. :)

**Comment by jazzdd86** [comment]
I just uploaded a new version of the image. Now you are able to define alpine packages required by your application. Just copy a file named "requirements_image.txt" into your app folder and include your packages written in your first post.
This will install those packages on the first run of your container.
If this solves your issue, you can close it.
